works = {
    mandalas: {
        name: 'Mandalas Sonoras',
        year: '2020',
        description: 'Mandalas Sonoras é uma plataforma open source e interativa que a partir do sensor de som cria padrões de forma e cor. Através da percepção de ritmo, volume, e tonalidade do som são gerados grafismos que constroem mandalas em uma relação sinestésica.',
        tags: ['arte', 'code', 'front', 'video', 'audio', 'web'],
        
    },
    hypertexto: {
        name: 'Cidade Hypertexto',
        year: '2022',
        description: '',
        tags: ['arte', 'code', '3D', 'front', 'web'],
    },
    pixel: {
        name: 'Picture Element',
        year: '2021',
        description: 'A história do pixel do analógico ao digital',
        tags: [ 'arte', 'code', '3D', 'animation', 'video'],
    },
    movelab: {
        name: 'Laboratório de Movimento',
        year: '2021',
        description: '',
        tags: ['arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    carnedigital: {
        name: 'Acervo Carne Digital',
        year: '2019',
        description: '',
        tags: ['arte', 'code', 'font', 'web'],
    },
    mocap: {
        name: 'MOCAP: Interrogando Geografias da Dança - Building an International network for virtual dance collaboration',
        year: '2022',
        description: 'Goldsmith University of London . Online . mocapstreamer.live',
        tags: ['arte', 'code', '3D', 'video'],
    },
    chataround: {
        name: 'ChatAround',
        year: '2020',
        description: 'ChatAround é um ambiente de conversa com recursos completos de áudio, vídeo e compartilhamento de tela. Com sua resposta de áudio pela distância entre o usuário e a fonte, é perfeito para reuniões, encontros e eventos conectados em todo o mundo.',
        tags: ['code', 'front', 'tools', 'web'],
    },
    hostedplayer: {
        name: 'Hosted Player',
        year: '2022',
        description: 'Hosted Player: Revisitando a obra network performance for a swimmer "Hosted" de Olia Lialina. Pedro Rocha. 2022.',
        tags: ['arte', 'code', 'tools', 'web'],
    },
    olhosquemeviramantes: {
        name: '',
        year: '2019',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    oss: {
        name: 'Oficina de Síntese de Som',
        year: '2024',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    voicereader: {
        name: 'Assistant voice reader',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    QRCoder: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    wave: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    void: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    sucochar: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    maxxichar: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    analogsynth: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    syntvs: {
        name: 'Syntelevision',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    museuragatanga: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    synthsim: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
    drinky: {
        name: '',
        year: '',
        description: '',
        tags: ['analog', 'arte', 'code', '3D', 'front', 'animation', 'video', 'tools', 'audio', 'web'],
    },
}